# GitHub Actions documentation:
# https://docs.github.com/en/actions

name: CI

on:
  push:
    branches: master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  org:
    uses: peopledoc/.github/.github/workflows/js--emberjs-addons-ci.yml@main
    with:
      nodejs_version: 14
      ember_try_scenarios: "[
          'ember-lts-3.28',
          'ember-lts-4.4',
          'ember-release',
          'ember-beta',
          'ember-canary',
          'ember-classic',
          'embroider-safe',
          'embroider-optimized',
        ]"
